### PR TITLE
DDLPB interface

### PR DESCRIPTION
**Pull request by mnottoli**
- Fixed a few inconsistencies in the ddLPB interface
- Created an energy subroutine for each model
- Moved the 4 pi scaling factor inside the ddLPB routines

### CODE REVIEW

**Comment by mfherbst** [comment]
I finished implementing the pyside interfaces. Along the way I found a few issues:

- I had to disable FMM, otherwise I got strange memory errors
- There is a sign discrepancy between the e / gradphi returned by mkrhs and build_e, which I noted in my tests. @mnottoli I know we talked about this briefly, but I just wanted to verify this is intended behaviour to ensure the tests are correct.

**Comment by mfherbst** [comment]
Also by default we now use more warnings. This can be disabled though using a CMake option.

**Comment by mnottoli** [comment]
Thanks for fixing the sign discrepancy.
I will look into the FMM issue tomorrow.

Regarding kappa, you guessed correctly, it is not so easy to prepare a table, but we can provide a tool to compute it easily, more will follow by email.

**Comment by mfherbst** [comment]
@mnottoli  Ready to merge from my end.

**Pull request merged**
